image: node:7

cache:
  paths:
    - node_modules/

stages:
- build
- deploy

staging-build:
  stage: build
  environment:
    name: staging
  only:
  - next
  script:
  - mkdir secret
  - echo $GOOGLEAPI_CLIENT_CREDENTIALS_STAGING > secret/client.json
  - yarn
  - yarn build
  - cd functions
  - yarn
  - yarn build
  - cd ..

staging-deploy:
  stage: deploy
  environment:
    name: staging
  only:
  - next
  script:
  - yarn deploy-all -- --project staging --token "$FIREBASE_CI_TOKEN"
