image: node:8

stages:
- build
- test
- deploy

before_script:
- mkdir secret
- yarn config set cache-folder .yarn-cache
- yarn
- cd functions && yarn && cd ..

after_script:
- rm -rf secret

cache:
  untracked: true
  key: "$CI_PROJECT_ID/NODE_8"
  paths:
  - .yarn-cache

variables:
  COMMIT_SHA: $CI_COMMIT_SHA

build:
  stage: build
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $ORIGIN
  artifacts:
    paths:
    - dist/
    - functions/index.js
  only:
  - next
  - master
  script:
  # Build config/secrets
  - echo $ORIGIN > secret/origin.txt
  - echo $GOOGLEAPI_CLIENT_CREDENTIALS > secret/client.json
  - echo $FIREBASE_CONFIG > secret/firebase-config.json
  # build
  - yarn build
  - cd functions && yarn build && cd ..

test-functions:
  stage: test
  script:
  - cd functions && yarn test && cd ..

deploy:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $ORIGIN
  only:
  - next
  - master
  script:
  - yarn deploy-all -- --project $CI_ENVIRONMENT_SLUG --token "$FIREBASE_CI_TOKEN"
