image: node:7

stages:
- build
- deploy

before_script:
- mkdir secret
- yarn config set cache-folder .yarn-cache
- yarn
- cd functions && yarn && cd ..

after_script:
- rm -rf secret

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
  - .yarn-cache

staging-build:
  stage: build
  environment:
    name: staging
  artifacts:
    paths:
    - dist/
    - functions/index.js
  only:
  - next
  script:
  # Disable Google analytics for the staging site
  - GOOGLE_ANALYTICS_ID=
  # Build config/secrets
  - echo $ORIGIN_STAGING > secret/origin.txt
  - echo $GOOGLEAPI_CLIENT_CREDENTIALS_STAGING > secret/client.json
  - echo $FIREBASE_CONFIG_STAGING > secret/firebase-config.json
  # build
  - yarn build
  - cd functions && yarn build && cd ..

staging-deploy:
  stage: deploy
  environment:
    name: staging
  only:
  - next
  script:
  - yarn deploy-all -- --project staging --token "$FIREBASE_CI_TOKEN"

production-build:
  stage: build
  environment:
    name: production
  artifacts:
    paths:
    - dist/
    - functions/index.js
  only:
  - master
  script:
  # Build config/secrets
  - scho $ORIGIN_PRODUCTION > secret/origin.txt
  - echo $GOOGLEAPI_CLIENT_CREDENTIALS_PRODUCTION > secret/client.json
  - echo $FIREBASE_CONFIG_PRODUCTION > secret/firebase-config.json
  # build
  - yarn build
  - cd functions && yarn build && cd ..

production-deploy:
  stage: deploy
  environment:
    name: production
  only:
  - master
  script:
  - yarn deploy-all -- --project production --token "$FIREBASE_CI_TOKEN"
