// auth
export const UPDATE_AUTH_STATE = 'auth/UPDATE_AUTH_STATE';

// calendars
export const UPDATE_CALENDAR = 'calendars/UPDATE_CALENDAR';
export const UPDATE_CALENDARS_SUBSCRIPTION =
  'calendars/UPDATE_CALENDAR_SUBSCRIPTION';

// planner
export const UPDATE_PLANNER_SESSION = 'planner/UPDATE_PLANNER_SESSION';
export const UPDATE_PLANNER_SUBSCRIPTION =
  'planner/UPDATE_PLANNER_SUBSCRIPTION';
